spring:
  application:
    name: ai-app-builder

  datasource:
    url: jdbc:postgresql://localhost:9000/ai_app_builder_db
    username: navneetsb
    password: admin0000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    user:
      name: navneetsb
      password: admin123
jwt:
  secret-key: a8F9xK2mP7qL4vN1zR6tY3uW8bH5cJ0sD9eG2kLmQ7pX4rT1