spring:
  application:
    name: ai-app-builder

  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: ${env.JWT_SECRET_KEY}